[#ftl]
[@b.head/]
[#assign weekdays={"1":"周一","2":'周二',"3":'周三',"4":'周四',"5":'周五',"6":'周六',"7":'周日'}/]
[@b.grid items=activities var="activity"]
  [@b.gridbar]
    bar.addItem("导出巡课设备文件",action.method("devices",null,null,"_blank"));
  [/@]
  [@b.row]
    [@b.col width="3%" title="序号"]${activity_index+1}[/@]
    [@b.col property="clazz.crn" title="课程序号" width="6%"]${activity.clazz.crn}[/@]
    [@b.col property="clazz.course.code" title="课程代码" width="8%" /]
    [@b.col property="clazz.course.name" title="课程名称"/]
    [@b.col property="clazz.courseType.name" title="课程类别" width="14%" /]
    [@b.col title="授课教师" width="8%" ]
      [#list activity.teachers as t]${t.name}[#sep]&nbsp;[/#list]
    [/@]
    [@b.col title="教师院系" width="8%" ]
      [#list activity.teachers as t]${(t.department.shortName)!t.department.name}[#sep]&nbsp;[/#list]
    [/@]
    [@b.col title="上课时间" width="8%" ]
     ${weekdays[activity.time.weekday.id?string]} ${activity.beginUnit}~${activity.endUnit}
    [/@]
    [@b.col title="教室" width="15%"]
      [#list activity.rooms as r]${r.name}[#assign devices=r.activeDevices(semester)][#if devices?size>0](${devices?size})[/#if][#sep]&nbsp;[/#list]
    [/@]
    [@b.col property="clazz.enrollment.stdCount" title="人数" width="5%" /]
  [/@]
[/@]
[@b.foot/]
